apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sof-app02
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
        #      - analysis:
         # templateName: sof-app02-analysis
         # arguments: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sof-app02
  template:
    metadata:
      labels:
        app: sof-app02
        rollouts-pod-template-hash: e0b1dc1bb0edf9e161d17d7ba1565844b64e8e37 #pragma: allowlist secret
    spec:
      containers:
      - name: sof-app02
#        image: dimitardd/dimitar-app02:b07c7bf5c0df29652dd1c86ec06463770388fb98  #Green
#        image: dimitardd/dimitar-app02:57bb7e9bcd3546159be0917df7e87526d8170140 #Blue
        image: dimitardd/dimitar-app02:e0b1dc1bb0edf9e161d17d7ba1565844b64e8e37  #Fresh
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

