apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sof-app02
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sof-app02
  template:
    metadata:
      labels:
        app: sof-app02
    spec:
      containers:
      - name: sof-app02
#        image: dimitardd/dimitar-app02:4fb3e4a57b0eb02324905c3cd293a83754a32057
        image: dimitardd/dimitar-app02:4d8f5c0aba5f446b4822a1b79c561c3e18850cba
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
