- name: Build, push and run Docker image M1-3-1 Ansible
  hosts: localhost
  gather_facts: no
  vars:
    image_name: "dimitardd/dimitar-app02"
    image_tag: "v4.1"
    listen_port: "5000"
    dockerpath: "/opt/telerik/build"
    gitbanch: "dimitardd-281024"
  
  tasks:
    - name: Get Dockerfile lates version!
      git:
        repo: git@github.com:dimitardd/devops-programme.git
        dest: "{{ dockerpath }}"
        version: "{{ gitbanch }}"
        force: yes

    - name: Build Container Image!
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ dockerpath }}"
          dockerfile: Dockerfile
        source: build
        state: present
#        push: yes
    - name: tag_version
      docker_image:
        name: latest     # Equal to name in build task.
        repository: "{{ image_name }}"
