apiVersion: apps/v1
kind: Deployment
metadata:
  name: sof-app01
  namespace: sof-app01
  labels:
    app: sof-app01
spec:
  replicas: 9
  selector:
    matchLabels:
      app: sof-app01
  template:
    metadata:
      labels:
        app: sof-app01
    spec:
      containers:
        - name: sof-app01
          #          image: dimitardd/dimitar-app02:e0b1dc1bb0edf9e161d17d7ba1565844b64e8e37 #Auto deplayed from build
          #          image: dimitardd/dimitar-app02:b07c7bf5c0df29652dd1c86ec06463770388fb98 #Green
          image: dimitardd/dimitar-app02:56e460596f70a74313417d3b7a6c605784e6b083 #Blue
          #          image: dimitardd/dimitar-app01:e0b1dc1bb0edf9e161d17d7ba1565844b64e8e37  #Yellow
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
