apiVersion: apps/v1
kind: Deployment
metadata:
  name: sof-app01
  labels:
    app: sof-app01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: imitardd/dimitar-app02
          ports:
            - containerPort: 80