apiVersion: apps/v1
kind: Deployment
metadata:
  name: sof-app02
  namespace: sof-app02
  labels:
    app: sof-app02
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: dimitardd/dimitar-app02
          ports:
            - containerPort: 3000
