apiVersion: v1
kind: Secret
metadata:
  name: sof-app01-tls
  namespace: sof-app01
type: kubernetes.io/tls
data:
  tls.crt: ${{ secrets.SOF_APP01_TLS_CERT }}
  tls.key: ${{ secrets.SOF_APP01_TLS_KEY }}
  