apiVersion: v1
kind: Secret
metadata:
  name: sof-app01-tls
  namespace: sof-app01
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "sof-app01"
    vault.hashicorp.com/agent-inject-secret-tls.crt: "kv/sof-app01"
    vault.hashicorp.com/agent-inject-secret-tls.key: "kv/sof-app01"
    vault.hashicorp.com/agent-inject-template-tls.crt: |
      {{- with secret "kv/sof-app01" -}}
      {{ .Data.data.cert}}
      {{- end -}}
    vault.hashicorp.com/agent-inject-template-tls.key: |
      {{- with secret "kv/sof-app01" -}}
      {{ .Data.data.key}}
      {{- end -}}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""

