name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    paths:
      - 'terraform/**'
      - 'github/workflows/github-action-terraform.yml'
    branches:
      - main
      - dimitardd-*
jobs:
 Terraform-init-plan:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5
      - name: Terraform Init
        run: |
            ls -la
            pwd
            terraform init
      - name: Terraform Plan
        run: terraform plan
