name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 Pylint:
   runs-on: self-hosted
   steps:
     - name: Check out repo
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Set Node version
       uses: actions/setup-node@v4
       with:
         node-version: '20'
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
         python-version: '3.10.5'
         cache: 'pip'
     - run: |
            pip install pylint black flake8 flask
            npm install -g markdownlint-cli editorconfig-checker
     - name: Check Editorconfig
       run: editorconfig-checker
     - name: Analysing the code with pylint
       run: pylint --disable=C0111,C0114,C0115,C0116 $(git ls-files '*.py')
     - name: Markdownlint config file
       run: |
         echo '{
           "MD012": false,
           "MD013": false,
           "line-lenght": false
          }' > .markdownlint.json
     - name: Markdown lint check
       run: markdownlint '**/*.md' --ignore node_modules
 UnitTest:
    needs: Pylint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.5'
          cache: 'pip'
      - run: |
            pip install flask
      - name: Run app test
        run: |
          cd app
          python -m unittest app_test.py
 CheckforSecrets:
    needs: Pylint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  CheckSAST:
#    needs: Pylint
#    name: SonarCloud
#    runs-on: self-hosted
     