name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 Pylint:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repo
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Set Node version
       uses: actions/setup-node@v4
       with:
         node-version: '20'
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
         python-version: '3.10'
         cache: 'pip'
     - run: |
            pip install pylint black flake8 flask
            npm install -g markdownlint-cli editorconfig-checker
     - name: Check .editorconfig
       run: editorconfig-checker
     - name: Analysing the code with pylint
       run: pylint --disable=C0111,C0114,C0115,C0116 $(git ls-files '*.py')
     - name: Markdownlint config file
       run: |
         echo '{
           "MD013": false,
           "line-lenght": false
          }' > .markdownlint.json
     - name: Check markdown files
       run: markdownlint '**/*.md' --ignore node_modules
